### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by priocomdevops** [Imatic-IT/imatic-mantis-formatting#3]
I'm getting an 'Internal Application Error' when i try to install it in Mantis 2,24.3. I've extracted to plugins folder then tried to install. I've followed due naming procedure but no luck.

What am I missing please?
Thanks.

**Comment by nenadalm** [comment]
hi. you're supposed to install this plugin via composer: https://github.com/Imatic-IT/imatic-mantis-formatting/blob/master/composer.json#L2

it has one php dependency, so you probably didn't install that (If you install via composer, it will be taken care of for you).

so if you want to install this plugin just run something like:
```
composer install imatic-it/imatic-formatting
```

**Comment by priocomdevops** [comment]
Hi,

Many thanks for your response.

Unfortunately the way I'm set up at work I can't use Composer. I'm only able to install it through the rudimentary method. Which php dependency does it have?

Regards.

**Comment by nenadalm** [comment]
this one: https://github.com/Imatic-IT/imatic-mantis-formatting/blob/master/composer.json#L8

I'll close the ticket as installing the plugin not via composer is not supported.
